version: "3"

services: 
    db:
        image: postgres:12
        container_name: ecommercescrape_db
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ecommercescrape-db:/var/lib/postgresql/data
    redis:
        container_name: ecommercescrape_redis
        image: redis
    server:
        container_name: ecommercescrape_server
        image: docker.pkg.github.com/mubarak117136/ecommercescrape/ecommercescrape:dev
        environment:
            - DJANGO_SETTINGS_MODULE:ecommercescrape.settings.dev
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./:/app
            - ./server/celery/celerybeat.pid:/app/server/celery/celerybeat.pid
        ports:
            - "8000:8000"
        depends_on: 
            - db
    celery:
        container_name: ecommercescrape_celery
        image: docker.pkg.github.com/mubarak117136/ecommercescrape/ecommercescrape:dev
        command: celery -A ecommercescrape worker -l info
        environment:
            - DJANGO_SETTINGS_MODULE:ecommercescrape.settings.dev
        volumes:
            - ./server:/app/server
        depends_on:
            - db
            - redis
    celery-beat:
        container_name: ecommercescrape_celery_beat
        image: docker.pkg.github.com/mubarak117136/ecommercescrape/ecommercescrape:dev
        command: celery beat -A ecommercescrape --loglevel=INFO --pidfile="/app/server/celery/celerybeat.pid"
        environment:
            - DJANGO_SETTINGS_MODULE:ecommercescrape.settings.dev
        volumes:
            - ./server:/app/server
        depends_on:
            - db
            - redis
            - celery
volumes: 
    ecommercescrape-db: