version: "3"

services: 
    db:
        image: postgres:12
        container_name: ecommercescrape_db
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ecommercescrape-db:/var/lib/postgresql/data
    server:
        container_name: ecommercescrape_server
        image: docker.pkg.github.com/mubarak117136/ecommercescrape/ecommercescrape:dev
        environment:
            - DJANGO_SETTINGS_MODULE:ecommercescrape.settings.production
        command: gunicorn -w 3 ecommercescrape.wsgi -b 0.0.0.0:8000
        volumes:
            - ./server/.env:/app/server/.env
            - ./server/betop/static:/app/server/betop/static
            - ./server/betop/media:/app/server/betop/media
            - ./server/socket:/app/server/socket
        ports:
            - "8000:8000"
volumes: 
    ecommercescrape-db: