# Generated by Django 3.1.2 on 2021-03-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField(verbose_name='Website Link')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category')),
                ('brand', models.CharField(blank=True, max_length=250, null=True, verbose_name='Brand')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('old_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Price')),
                ('discount', models.CharField(blank=True, max_length=150, null=True, verbose_name='Discount')),
                ('price', models.CharField(blank=True, max_length=150, null=True, verbose_name='Price')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image link')),
            ],
        ),
    ]
