# Generated by Django 3.1.2 on 2021-03-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_url',
            field=models.URLField(blank=True, null=True, verbose_name='Detail Url'),
        ),
    ]
